services:
 #phpadmin sql managment
  phpmyadmin:
    container_name: PHPMYADMIN
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 3001:80

 #Wordpress server.
  wordpress:
    container_name: WORDPRESS-STIE
    image: wordpress:php7.4-apache
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=$MYSQL_HOST
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB_NAME
      - WORDPRESS_AUTH_KEY=$WORDPRESS_AUTH_KEY
      - WORDPRESS_SECURE_AUTH_KEY=$WORDPRESS_SECURE_AUTH_KEY
      - WORDPRESS_LOGGED_IN_KEY=$WORDPRESS_LOGGED_IN_KEY
      - WORDPRESS_NONCE_KEY=$WORDPRESS_NONCE_KEY
      - WORDPRESS_AUTH_SALT=$WORDPRESS_AUTH_SALT
      - WORDPRESS_SECURE_AUTH_SALT=$WORDPRESS_SECURE_AUTH_SALT
      - WORDPRESS_LOGGED_IN_SALT=$WORDPRESS_LOGGED_IN_SALT
      - WORDPRESS_NONCE_SALT=$WORDPRESS_NONCE_SALT
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 80:80
