version: '3.7'

services:
 #phpadmin sql managment
  phpmyadmin:
    container_name: PHPMYADMIN
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 3001:80

 #Wordpress server.
  wordpress:
    container_name: WORDPRESS-STIE
    image: wordpress:php7.4-apache
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=$MYSQL_HOST
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB_NAME
    volumes:
      - ./wp-content:/var/www/html
    ports:
      - 80:80
