services:
  #phpadmin sql managment
   phpmyadmin:
     container_name: PHPMYADMIN
     image: phpmyadmin/phpmyadmin
     environment:
       - PMA_HOST=db:3306
       - MYSQL_USER=$MYSQL_USER
       - MYSQL_PASSWORD=$MYSQL_PASSWORD
     ports:
       - 3001:80
     depends_on:
       - db
 
  #Wordpress server.
   wordpress:
     container_name: WORDPRESS-STIE
     image: wordpress:php7.4-apache
     env_file: .env
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER=$MYSQL_USER
       - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
       - WORDPRESS_DB_NAME=$MYSQL_DB_NAME
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - 80:80
     depends_on:
       - db
 
   db:
     image: mysql:5.7
     env_file: .env
     environment:
       - MYSQL_DATABASE=$MYSQL_DB_NAME
     volumes:
       - ./MysqlBb:/var/lib/mysql
     ports:
       - 3306:3306
